# Generated by Django 5.2.15 on 2026-07-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='severity',
            field=models.CharField(choices=[('low', 'Low - Minor Inconvenience'), ('medium', 'Medium - Some feathers are fuffled here.'), ('high', 'High - This is seriously a problem'), ('critical', ' Critical - Its the end of the world as we know it')], default='low', max_length=20),
        ),
    ]
