# Generated by Django 5.2.15 on 2026-07-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_supportticket_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='ticket_id_string',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
