# Generated by Django 5.2.15 on 2026-07-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportticket_ticket_id_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_id_string',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
