# Generated by Django 5.2.15 on 2026-07-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_supportticket_ticket_id_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
