# Generated by Django 5.2.15 on 2026-07-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id_string',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id_string',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
